data_entry:
- NAME: NGUYEN NGOC TRANG
  SAP: '2824206'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: VU THI HOE
  SAP: '3349561'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: NGUYEN THI THANH TAM
  SAP: '3322285'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: TUYET LAN
  SAP: '3212044'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  GENDER: FEMALE
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- NAME: VAN ANH
  SAP: '3294389'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  GENDER: FEMALE
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- NAME: HA THI THANH VAN
  SAP: '691461'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN60
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: TRAN THU THAO
  SAP: '3307871'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN61
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: NGUYEN THI KIM NGAN
  SAP: '2495170'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN62
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: LE THI THUY HA
  SAP: '1080662'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN82
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: TRUONG NGOC MAI DUNG
  SAP: '2978308'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN82
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: NGUYEN THI KIEU NUONG
  SAP: '3308714'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN82
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: PHAM THUY THANH TRUC
  SAP: '1216105'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN83
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: LE THI HIEU
  SAP: '3225301'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN83
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: LE CAO THUY LINH
  SAP: '3225303'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN83
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: NGUYEN THI THU TRANG
  SAP: '3560449'
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN62
  GENDER: FEMALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
path_report: D:\Download\Report Scan Verify Shiftly (RCV).xlsm
selected_verify:
- '3601183'
- '3212044'
- '3322289'
selected_keyins:
- '2495170'
- '2495170'
- '2495170'
verify:
- NAME: LE ANH TUAN
  SAP: '3294344'
  ROLE: VERIFY
  SHIFT_WORKING: VN60
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: VO HO TAN LINH
  SAP: '3294333'
  ROLE: VERIFY
  SHIFT_WORKING: VN61
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: VO LE HOANG HIEU
  SAP: '3212020'
  ROLE: VERIFY
  SHIFT_WORKING: VN62
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: NGUYEN KHAC MINH PHUONG
  SAP: '3601183'
  ROLE: VERIFY
  SHIFT_WORKING: VN82
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: HA TRUONG HOANG GIA
  SAP: '3302117'
  ROLE: VERIFY
  SHIFT_WORKING: VN82
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: BUI CHI NGHIA
  SAP: '3210272'
  ROLE: VERIFY
  SHIFT_WORKING: VN83
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: KIEN THAI VY THE KHOA
  SAP: '3222451'
  ROLE: VERIFY
  SHIFT_WORKING: VN83
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: NGUYEN THI THANH TAM
  SAP: '3322285'
  ROLE: VERIFY
  SHIFT_WORKING: VN02
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: TUYET LAN
  SAP: '3212044'
  ROLE: VERIFY
  SHIFT_WORKING: VN02
  GENDER: MALE
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- NAME: VAN ANH
  SAP: '3294389'
  ROLE: VERIFY
  SHIFT_WORKING: VN02
  GENDER: MALE
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- NAME: DAT
  SAP: '3322289'
  ROLE: VERIFY
  SHIFT_WORKING: VN02
  GENDER: FEMALE
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- NAME: TRUONG NGOC MAI DUNG
  SAP: '2978308'
  ROLE: VERIFY
  SHIFT_WORKING: VN82
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: NGUYEN THI KIEU NUONG
  SAP: '3308714'
  ROLE: VERIFY
  SHIFT_WORKING: VN82
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: PHAM THUY THANH TRUC
  SAP: '1216105'
  ROLE: VERIFY
  SHIFT_WORKING: VERIFY
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- NAME: LE THI HIEU
  SAP: '3225301'
  ROLE: VERIFY
  SHIFT_WORKING: VN83
  GENDER: MALE
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
email_from: phuong_nguyen1183@JABIL.COM
password: Conmeobo12345678@

LEAD_EMAIL:
 -  HONG_NGUYEN4147@JABIL.COM
 -  THAM_NGUYEN3@JABIL.COM
 -  BIEU_VO@JABIL.COM
 -  NAM_NGO@JABIL.COM
 -  KHANH_TRUONG@JABIL.COM
 -  LAN_PHAN@JABIL.COM
     