data_entry:
- SAP: '2824206'
  NAME: NGUYEN NGOC TRANG
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3349561'
  NAME: VU THI HOE
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3322285'
  NAME: NGUYEN THI THANH TAM
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3212044'
  NAME: TUYET LAN
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- SAP: '3294389'
  NAME: VAN ANH
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN02
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- SAP: '691461'
  NAME: HA THI THANH VAN
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN60
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3307871'
  NAME: TRAN THU THAO
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN61
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '2495170'
  NAME: NGUYEN THI KIM NGAN
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN62
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '1080662'
  NAME: LE THI THUY HA
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN82
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '2978308'
  NAME: TRUONG NGOC MAI DUNG
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN82
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3308714'
  NAME: NGUYEN THI KIEU NUONG
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN62
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '1216105'
  NAME: PHAM THUY THANH TRUC
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN60
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3225301'
  NAME: LE THI HIEU
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN83
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3225303'
  NAME: LE CAO THUY LINH
  GENDER: FEMALE
  ROLE: DATA ENTRY
  SHIFT_WORKING: VN61
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
path_report: C:\Users\3601183\Desktop\Report Scan Verify Shiftly (RCV).xlsm
selected_verify:
- '3601183'
- '3294344'
selected_keyins:
- 5
verify:
- SAP: '3294344'
  NAME: LE ANH TUAN
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN60
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3294333'
  NAME: VO HO TAN LINH
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN61
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3212020'
  NAME: VO LE HOANG HIEU
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN62
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3601183'
  NAME: NGUYEN KHAC MINH PHUONG
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN82
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3302117'
  NAME: HA TRUONG HOANG GIA
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN82
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3210272'
  NAME: BUI CHI NGHIA
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN83
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3222451'
  NAME: KIEN THAI VY THE KHOA
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN83
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3322285'
  NAME: NGUYEN THI THANH TAM
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN02
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3212044'
  NAME: TUYET LAN
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN02
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- SAP: '3294389'
  NAME: VAN ANH
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN02
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- SAP: '3322289'
  NAME: DAT NGUYEN
  GENDER: FEMALE
  ROLE: VERIFY
  SHIFT_WORKING: VN02
  LOCATION: TMS
  ON_OFF: On duty
  SLOC: null
- SAP: '2978308'
  NAME: TRUONG NGOC MAI DUNG
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN82
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3308714'
  NAME: NGUYEN THI KIEU NUONG
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN82
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '1216105'
  NAME: PHAM THUY THANH TRUC
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VERIFY
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
- SAP: '3225301'
  NAME: LE THI HIEU
  GENDER: MALE
  ROLE: VERIFY
  SHIFT_WORKING: VN83
  LOCATION: TBS
  ON_OFF: On duty
  SLOC: null
email_from: phuong_nguyen1183@JABIL.COM
password: Conmeobo12345678@
LEAD_EMAIL:
- HONG_NGUYEN4147@JABIL.COM
- THAM_NGUYEN3@JABIL.COM
- BIEU_VO@JABIL.COM
- NAM_NGO@JABIL.COM
- KHANH_TRUONG3@JABIL.COM
- LAN_PHAN@JABIL.COM
